/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#abadae",
        "on-secondary-container": "#31486b",
        "error-dim": "#9f0519",
        "surface-container-highest": "#dadddf",
        "on-primary-fixed-variant": "#00276b",
        "secondary-container": "#bbd3fd",
        "secondary-dim": "#395074",
        "on-tertiary-fixed-variant": "#004a5a",
        secondary: "#465c80",
        "surface-variant": "#dadddf",
        "surface-container": "#e6e8ea",
        "on-tertiary": "#e0f6ff",
        "tertiary-fixed-dim": "#28c0e4",
        "surface-container-low": "#eff1f2",
        "surface-bright": "#f5f6f7",
        "on-secondary": "#eff2ff",
        "secondary-fixed": "#bbd3fd",
        "tertiary-fixed": "#40cef3",
        "primary-container": "#789dff",
        background: "#f5f6f7",
        "inverse-on-surface": "#9b9d9e",
        "surface-container-high": "#e0e3e4",
        "on-primary-container": "#001f57",
        "primary-fixed-dim": "#618eff",
        "on-error-container": "#570008",
        "on-error": "#ffefee",
        "on-secondary-fixed": "#1d3557",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d1d5d7",
        "secondary-fixed-dim": "#aec5ee",
        "primary-dim": "#0048b5",
        "inverse-surface": "#0c0f10",
        "on-primary-fixed": "#000000",
        tertiary: "#006479",
        "on-tertiary-container": "#00414f",
        "primary-fixed": "#789dff",
        "inverse-primary": "#5c8bff",
        "error-container": "#fb5151",
        "on-secondary-fixed-variant": "#3a5175",
        primary: "#0253cd",
        "on-tertiary-fixed": "#002a34",
        "surface-tint": "#0253cd",
        "tertiary-container": "#40cef3",
        error: "#b31b25",
        "tertiary-dim": "#00576a",
        "on-background": "#2c2f30",
        "on-surface-variant": "#595c5d",
        "on-surface": "#2c2f30",
        surface: "#f5f6f7",
        "on-primary": "#f1f2ff",
        outline: "#757778",
        // Dark mode overrides via CSS vars handled separately
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
